---
- name: Test Commands
  hosts: ansible-test
  gather_facts: no
  tasks:
    - name: Get flash directory
      ios_command:
        commands: dir | i bin
      register: dir
    # - debug:
    #     var: dir
    #     msg: "Value is echo {{ item }} | awk '{print $9}'"
    #   with_items: "{{ dir.stdout_lines }}"

    - name: Parse output
      # shell: "echo {{dir.stdout_lines}} | awk '{print $9}' >> out.txt"
      shell: "echo {{ item }} | awk '{print $9}'"
      with_items: "{{ dir.stdout_lines }} "
      register: awk_output
      changed_when: No
    - debug:
        # var: awk_output.results[0].stdout_lines, awk_output.results[1].stdout_lines
        msg: "Value is {{item.stdout}}"
      loop: "{{awk_output.results}}"
      loop_control:
        label: "Output"