---
- name: Diff playbook
  hosts: switches-3650
  gather_facts: no
  tasks:
    - name: Compare config to reference
      ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', 'backup/master.cfg') }}"       
        # intended_config: "{{ lookup('file', '/home/eng_fcc/ansible/cisco-ansible/backup/master.cfg') }}"
      diff: true  