---
- name: Gather network device facts
  hosts: all
  gather_facts: no
  tasks:
    - name: gather facts
      ios_facts:
        gather_subset: hardware
    
    - name: output facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}
         image is {{ ansible_net_filesystems}} "
# ---

# - name: Network Getting Started First Playbook
#   connection: network_cli
#   hosts: all
#   tasks:

#     - name: Get config for VyOS devices
#       vyos_facts:
#         gather_subset: all

#     - name: Display the config
#       debug:
#         msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"