---
- name: copy file to flash.
  hosts: LIN-WLFG-9300-F9-01
  gather_facts: no
  tasks:
  - net_put:
      src: files/cat9k_iosxe.16.06.04.SPA.bin
      protocol: scp
      dest : flash:/cat9k_iosxe.16.06.04.SPA.bin